"""Output compatibility against fixtures generated by the pre-refactor
scripts/run_session.py (same args: subject 1, session 1, 2 trials,
rest 0.2/0.2, seed 42, --no-lsl --no-beep, comment 'fixture').

Timestamps naturally differ between runs, so they are normalized; every
other byte of structure (key names, key order, values, CSV headers and
non-timing cells) must match the old code exactly.
"""
import csv
import json
import os
import re

from conftest import run_happy_path

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")

TIME_KEYS = {"t_wall", "t_lsl", "t_rest_pre", "t_plan", "t_solve", "t_rest_post",
             "plan_s", "solve_s", "break_s"}
STAMP_KEYS = {"started", "ended"}


def normalize(obj, key=None):
    if isinstance(obj, dict):
        return {k: normalize(v, k) for k, v in obj.items()}
    if isinstance(obj, list):
        return [normalize(v, key) for v in obj]
    if key in TIME_KEYS and isinstance(obj, (int, float)):
        return "<t>"
    if key in STAMP_KEYS:
        return "<stamp>"
    if key == "seed" and isinstance(obj, int):
        return "<seed>" if obj != 42 else 42
    return obj


def test_json_log_matches_pre_refactor_schema(harness):
    s, rec, sink, beeper, store, clock = harness()
    run_happy_path(s, rec)

    with open(os.path.join(FIXTURES, "pre_refactor_log.json")) as f:
        expected = json.load(f)
    got = store.read_log(s.base)

    assert normalize(got) == normalize(expected)
    # key order matters for byte compatibility of the dumped JSON
    assert list(got.keys()) == list(expected.keys())
    for g, e in zip(got["trials"], expected["trials"]):
        assert list(g.keys()) == list(e.keys())
    for g, e in zip(got["markers"], expected["markers"]):
        assert list(g.keys()) == list(e.keys())


def read_csv(path):
    with open(path) as f:
        rows = list(csv.reader(f))
    return rows


def norm_cells(rows, timing_cols, date_cols, header):
    idx = {name: i for i, name in enumerate(header)}
    out = [list(header)]
    for row in rows:
        row = list(row)
        for c in timing_cols:
            if row[idx[c]] != "":
                assert re.fullmatch(r"-?\d+(\.\d+)?", row[idx[c]]), (c, row)
                row[idx[c]] = "<t>"
        for c in date_cols:
            row[idx[c]] = "<date>"
        # the log basename embeds a timestamp
        if "log" in idx:
            row[idx["log"]] = re.sub(r"\d{8}_\d{6}$", "<stamp>", row[idx["log"]])
        out.append(row)
    return out


def test_csvs_match_pre_refactor_schema(harness):
    s, rec, sink, beeper, store, clock = harness()
    run_happy_path(s, rec)

    for name, timing, dates in [
        ("solves", ["plan_s", "solve_s", "break_s"], ["date"]),
        ("sessions", ["mean_solve_s", "best_solve_s"], ["date"]),
    ]:
        exp = read_csv(os.path.join(FIXTURES, f"pre_refactor_{name}.csv"))
        got = read_csv(getattr(store, f"{name}_csv"))
        assert got[0] == exp[0], f"{name}.csv header changed"
        assert norm_cells(got[1:], timing, dates, got[0]) == \
               norm_cells(exp[1:], timing, dates, exp[0]), f"{name}.csv rows differ"
